// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhvkblhyieybgwvdjevw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodmtibGh5aWV5Ymd3dmRqZXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDI4MDAsImV4cCI6MjA2NzcxODgwMH0.fXjD0WkdXS0-qwogyR0Rre_Oh8Jj6RrGJudGGPYBSWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});